In [2]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Reading the Data

In [3]:
movies = pd.read_csv('data/tmdb_movies_50k.csv')
movies['index'] = movies.index
movies.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords,index
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",0
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",1
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",2
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",3
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",4


# Filling the Missing Spaces

In [4]:
movies.isnull().sum()

id                          0
title                       0
vote_average                0
vote_count                  0
status                      0
release_date               13
revenue                     0
runtime                     0
adult                       0
backdrop_path            2382
budget                      0
homepage                37989
imdb_id                   212
original_language           0
original_title              0
overview                  456
popularity                  0
poster_path               152
tagline                 23592
genres                    222
production_companies     3668
production_countries     1241
spoken_languages          521
keywords                10926
index                       0
dtype: int64

In [5]:
selected_features = ['genres', 'keywords', 'overview', 'tagline']

In [6]:
for feature in selected_features:
    movies[feature] = movies[feature].fillna('')

# Combining the Useful Features

In [7]:
combined_features = movies['genres']+ ' ' +movies['keywords']+ ' ' +movies['overview']+ ' ' +movies['tagline']
combined_features.head()

0    Action, Science Fiction, Adventure rescue, mis...
1    Adventure, Drama, Science Fiction rescue, futu...
2    Drama, Action, Crime, Thriller joker, sadism, ...
3    Action, Adventure, Fantasy, Science Fiction fu...
4    Science Fiction, Action, Adventure new york ci...
dtype: str

In [8]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2441135 stored elements and shape (50000, 72277)>
  Coords	Values
  (0, 1477)	0.051622313341542644
  (0, 56552)	0.06498488374475304
  (0, 23055)	0.06476521715431247
  (0, 1743)	0.06005731523820862
  (0, 53511)	0.09500833024715055
  (0, 41968)	0.0887776497976222
  (0, 19017)	0.17765582512599815
  (0, 2147)	0.11384297703171743
  (0, 47285)	0.08947672557944458
  (0, 24251)	0.086781544706013
  (0, 68725)	0.12981628811645926
  (0, 52293)	0.09644705680971286
  (0, 34894)	0.09787012639164519
  (0, 48508)	0.13077019287885439
  (0, 60611)	0.10608680646850573
  (0, 2532)	0.14816092472503323
  (0, 39402)	0.12655821960461647
  (0, 10471)	0.08551946345911703
  (0, 14833)	0.10162497715362072
  (0, 28812)	0.1091514077319487
  (0, 40933)	0.1067399342469036
  (0, 3920)	0.15291478979209847
  (0, 38054)	0.09486811629123115
  (0, 3189)	0.09538753222639484
  (0, 10071)	0.08968644969478011
  :	:
  (49999, 24587)	0.0648805378320268
  (49999, 13243

# Cosine Similarity

In [9]:
similarity = cosine_similarity(feature_vectors)
print(similarity)
print(similarity.shape)

[[1.         0.05940984 0.04339879 ... 0.02254332 0.02554874 0.01736646]
 [0.05940984 1.         0.01944896 ... 0.04300058 0.01351944 0.00800375]
 [0.04339879 0.01944896 1.         ... 0.02533356 0.03391326 0.01631233]
 ...
 [0.02254332 0.04300058 0.02533356 ... 1.         0.04266601 0.01486623]
 [0.02554874 0.01351944 0.03391326 ... 0.04266601 1.         0.0189678 ]
 [0.01736646 0.00800375 0.01631233 ... 0.01486623 0.0189678  1.        ]]
(50000, 50000)


# Getting the Movie Name from User

In [18]:
movie_name = input('Enter your favourite movie name: ')

In [19]:
list_of_all_titles = movies['title'].tolist()

In [20]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Avengers: Infinity War', 'Avengers Grimm: Time Wars', 'Mazinger Z: Infinity']


In [21]:
close_match = find_close_match[0]
print(close_match)

Avengers: Infinity War


In [22]:
index_of_the_movie = movies[movies.title == close_match]['index'].values[0]
print(index_of_the_movie)

6


# Finding the Similarity Score

In [23]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse=True)

# Suggesting the Movies

In [24]:
print("Movies suggested for you : \n")

i = 1

for movie in sorted_similar_movies[1:31]:
    index = movie[0]
    title_of_the_movie = movies[movies.index == index]['title'].values[0]
    if (i<31):
        print(i,'.', title_of_the_movie)
        i += 1

Movies suggested for you : 

1 . Avengers: Endgame
2 . Captain Marvel
3 . Guardians of the Galaxy Vol. 3
4 . Inhumans: The First Chapter
5 . Eternals
6 . Avengers: Age of Ultron
7 . Captain America: Civil War
8 . Marvel One-Shot: Item 47
9 . Marvel Studios: Assembling a Universe
10 . Doctor Strange in the Multiverse of Madness
11 . LEGO Marvel Super Heroes: Guardians of the Galaxy - The Thanos Threat
12 . Guardians of the Galaxy Vol. 2
13 . Marvel Studios' 2021 Disney+ Day Special
14 . Team Thor
15 . Green Lantern
16 . Marvel Studios Assembled: The Making of Doctor Strange in the Multiverse of Madness
17 . Peter's To-Do List
18 . Spider-Man: No Way Home
19 . The Flash
20 . Iron Man 3
21 . ISRA 88
22 . Thor: Ragnarok
23 . Thor: The Dark World
24 . Dark Phoenix
25 . Next Avengers: Heroes of Tomorrow
26 . Marvel One-Shot: Agent Carter
27 . Marvel One-Shot: The Consultant
28 . Guardians of the Galaxy
29 . Spider-Man: Far From Home
30 . The Avengers
